### ISSUE TITLE
Insert dummy values to DB

### ISSUE THREAD

**Issue by nandoks** [nandoks/TeacherPlan#14]
Some values like company, subjects, languages are needed to use some functionalities, I need help on how to add dummy values to the DB when working locally on a new pull of the project.

**Comment by Kraymer** [comment]
Have a look at https://docs.djangoproject.com/en/3.2/howto/initial-data/ ;)
If you knew this but still don't see how to do, then please be more specific.

**Comment by nandoks** [comment]
That's exactly what I needed.
Should I make one fixture for every app that I need initial values or one single fixture for the whole project would be ok?

**Comment by Kraymer** [comment]
In general with Django you want your apps to be as compartmentalized as possible, so one fixture for every app.
