### ISSUE TITLE
.pyc should not be commited in git

### ISSUE THREAD

**Issue by Kraymer** [nandoks/TeacherPlan#3]
~~~
Fast-forward
 TeacherPlan/__pycache__/settings.cpython-39.pyc                                | Bin 2601 -> 0 bytes
 TeacherPlan/__pycache__/urls.cpython-39.pyc        
~~~

**Comment by nandoks** [comment]
all .pyc files and __pycache__ folders added to .gitignore. I did a cach clear so files that were tracked will no longer be tracker by git and will no longer be pulled with the project
