### ISSUE TITLE
Specify auth passwords validators

### ISSUE THREAD

**Issue by Kraymer** [nandoks/TeacherPlan#4]
I created an account with "test" as password, the password should be rejected as too simple.

https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

**Comment by nandoks** [comment]
Would the built-in django validators be enough or a custom class would be required?
What kind of validators do we need? length, at least one uppercase and special character?

**Comment by Kraymer** [comment]
No need to get fancy : use the built-in validators configured as you judge reasonable for the security aspect.

**Comment by nandoks** [comment]
I added min_length=8 option to AUTH_PASSWORD_VALIDATORS and validate_password to register_form clean method so simple passwords wont be accepted.
Also added on register.html a way to show this errors to the user.
