### ISSUE TITLE
More intuitive UI to enter lesson time

### ISSUE THREAD

**Issue by Kraymer** [nandoks/TeacherPlan#5]
Display only the minutes that are multiples of five.

![Selection_999(1718)](https://user-images.githubusercontent.com/84227/124714888-9f459c00-df02-11eb-95a5-cb346ebec24e.png)

**Comment by nandoks** [comment]
Changed widget type to TimePicker with a stepping of 5 minutes.

**Comment by Kraymer** [comment]
Oui bien mieux comme ça :+1: 

Tips: tu peux citer les issues dans tes msgs de commit pour lier tout ça (si ça avait été fait un msg me permettant d'aller voir le commit serait apparu sur cette page). 
Par exemple : `fix #5: change widget type to TimePicker with a 5 min step`
