### ISSUE TITLE
Store sensitive data outside git

### ISSUE THREAD

**Issue by Kraymer** [nandoks/TeacherPlan#6]
Credentials and sensitive data like `SECRET_KEY` should not be stored in git, use a library like https://django-environ.readthedocs.io/en/latest/ to store them in an .env file that you'll add to your .gitignore list.

**Comment by nandoks** [comment]
I created an .env  file on my settings folder, pip installed django-environ and added secret key and DB credentials to .evn file. I double checked if .env files on .gitignore so it would not be tracker by git.

**Comment by Kraymer** [comment]
Good!

Maybe it could save some time if a dummy version of the `.env` was commited just to indicate the keys, eg :  

> DATABASE_NAME=
> DATABASE_USER=
> DATABASE_PASS=
> SECRET_KEY=

and then only the .env added to .gitignore to be sure it is not overwritten with an actual config

**Comment by Kraymer** [comment]
@nandoks I have the impression the .env ignore is not enforced by .gitignore is it the same for you ?

![Selection_999(1736)](https://user-images.githubusercontent.com/84227/125155409-eda3a680-e15f-11eb-83b1-94e2a3ecb8e4.png)

**Comment by Kraymer** [comment]
> and then only the .env added to .gitignore to be sure it is not overwritten with an actual config

In fact that was a bad suggestion from my part, you can't commit a file and then just _ignore_ it.
Maybe a compromise would be to commit the dummy version under another name like `.env.empty` and add instruction at top of the file like `# Please fill in variables below and rename file as .env`

**Comment by Kraymer** [comment]
yes, better this way
